In [2]:
from tqdm import tqdm
import pandas as pd

from helpers.file import save_file
from services.mysql import MySQLService

In [3]:
save_pipeline = True

In [4]:
mysql = MySQLService()

order_by_clause = "date ASC"
games_df = mysql.get_data("games", order_by_clause=order_by_clause)

season_games_plyrs = mysql.execute_query(f"""
    SELECT g.id as game_id, g.date, g.season, g.is_playoff, g.winner, g.home_id, p.name as player_name, g.away_id, pg.team_id, pg.player_id, pg.minutes, pg.pts, pg.fgm, pg.fga, pg.fg_pct, pg.fg3m, pg.fg3a, pg.fg3_pct, pg.ftm, pg.fta, pg.ft_pct, pg.oreb, pg.dreb, pg.reb, pg.ast, pg.stl, pg.blk, pg.tov, pg.pf, pg.plus_minus
    FROM player_games AS pg
        LEFT JOIN games as g on pg.game_id = g.id 
        LEFT JOIN players as p on pg.player_id = p.id 
    ORDER BY g.date ASC""")

display(games_df)
display(season_games_plyrs)

c:\Users\caiog\Projects\Personal\NBA-Predictor\src\services\mysql.py:28: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  resp = pd.read_sql_query(query, db)

,id,date,season,is_playoff,winner,home_id,home_team,home_pts,home_fgm,home_fga,...,away_oreb,away_dreb,away_reb,away_ast,away_stl,away_blk,away_tov,away_pf,home_odds,away_odds
0,21200001,2012-10-30,2012,0,H,1610612739,Cleveland Cavaliers,94,36,79,...,18,21,39,26,11,10,13,19,1.41,2.93
1,21200002,2012-10-30,2012,0,H,1610612748,Miami Heat,120,43,79,...,7,34,41,24,4,2,16,23,1.35,3.26
2,21200003,2012-10-30,2012,0,A,1610612747,Los Angeles Lakers,91,38,77,...,9,31,40,22,9,5,12,25,1.21,4.54
3,21200004,2012-10-31,2012,0,A,1610612761,Toronto Raptors,88,33,91,...,9,37,46,22,3,10,19,16,2.03,1.79
4,21200005,2012-10-31,2012,0,H,1610612755,Philadelphia 76ers,84,30,85,...,16,38,54,19,9,5,22,22,2.02,1.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15813,22401213,2024-12-13,2024,0,H,1610612743,Denver Nuggets,120,42,77,...,5,26,31,24,18,2,19,22,1.35,3.3
15814,22401214,2024-12-13,2024,0,A,1610612762,Utah Jazz,126,43,77,...,9,28,37,36,10,7,8,18,3.18,1.37
15815,22401215,2024-12-13,2024,0,A,1610612757,Portland Trail Blazers,116,42,82,...,13,28,41,32,5,6,15,13,2.37,1.61
15816,22401229,2024-12-14,2024,0,H,1610612749,Milwaukee Bucks,110,39,86,...,7,37,44,23,3,6,13,20,1.4,3.03
15817,22401230,2024-12-14,2024,0,H,1610612760,Oklahoma City Thunder,111,36,80,...,19,30,49,17,7,3,16,25,1.06,10.2

,game_id,date,season,is_playoff,winner,home_id,player_name,away_id,team_id,player_id,...,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,plus_minus
0,NaN,NaT,NaN,None,None,NaN,Andre Jackson Jr.,NaN,1610612749,1641748,...,0.000,0,0,0,0,0,0,0,0,-4
1,NaN,NaT,NaN,None,None,NaN,Chris Livingston,NaN,1610612749,1641753,...,0.000,0,0,0,0,0,0,0,0,-2
2,NaN,NaT,NaN,None,None,NaN,TyTy Washington Jr.,NaN,1610612749,1631102,...,0.000,0,0,0,0,0,0,0,0,-2
3,NaN,NaT,NaN,None,None,NaN,AJ Green,NaN,1610612749,1631260,...,0.000,0,1,1,0,0,0,0,0,6
4,NaN,NaT,NaN,None,None,NaN,Sam Hauser,NaN,1610612738,1630573,...,0.000,2,3,5,2,2,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335013,22401229.0,2024-12-14,2024.0,0,H,1.610613e+09,Clint Capela,1.610613e+09,1610612737,203991,...,0.000,2,6,8,0,1,4,1,4,-11
335014,22401229.0,2024-12-14,2024.0,0,H,1.610613e+09,Taurean Prince,1.610613e+09,1610612749,1627752,...,0.000,1,2,3,0,1,0,2,2,6
335015,22401229.0,2024-12-14,2024.0,0,H,1.610613e+09,Giannis Antetokounmpo,1.610613e+09,1610612749,203507,...,0.667,1,13,14,9,1,4,1,1,3
335016,22401230.0,2024-12-14,2024.0,0,H,1.610613e+09,Steven Adams,1.610613e+09,1610612745,203500,...,0.500,3,3,6,0,0,0,1,0,-1
335017,22401229.0,2024-12-14,2024.0,0,H,1.610613e+09,Bobby Portis,1.610613e+09,1610612749,1626171,...,0.000,1,8,9,2,0,1,0,2,-6

In [5]:
season_games_plyrs.columns

Index(['game_id', 'date', 'season', 'is_playoff', 'winner', 'home_id',
       'player_name', 'away_id', 'team_id', 'player_id', 'minutes', 'pts',
       'fgm', 'fga', 'fg_pct', 'fg3m', 'fg3a', 'fg3_pct', 'ftm', 'fta',
       'ft_pct', 'oreb', 'dreb', 'reb', 'ast', 'stl', 'blk', 'tov', 'pf',
       'plus_minus'],
      dtype='object')

In [ ]:
stats_columns = ['pts','fgm', 'fga', 'fg_pct', 'fg3m', 'fg3a', 'fg3_pct', 'ftm', 'fta',
    'ft_pct', 'oreb', 'dreb', 'reb', 'ast', 'stl', 'blk', 'tov', 'pf']

for i in tqdm(range(len(stats_columns))):
    stat = stats_columns[i]
    season_games_plyrs[f'{stat}_avg'] = (
        season_games_plyrs.sort_values(by=['player_id', 'date'])
                .groupby('player_id')[stat]
                .transform(lambda x: x.shift(1).rolling(window=5).mean())
    )

display(season_games_plyrs)

100%|██████████| 18/18 [00:12<00:00,  1.43it/s]

,game_id,date,season,is_playoff,winner,home_id,player_name,away_id,team_id,player_id,...,fta_avg,ft_pct_avg,oreb_avg,dreb_avg,reb_avg,ast_avg,stl_avg,blk_avg,tov_avg,pf_avg
0,NaN,NaT,NaN,None,None,NaN,Andre Jackson Jr.,NaN,1610612749,1641748,...,0.0,0.0000,0.8,1.4,2.2,1.4,1.0,0.2,1.0,3.0
1,NaN,NaT,NaN,None,None,NaN,Chris Livingston,NaN,1610612749,1641753,...,0.6,0.0000,0.2,0.2,0.4,0.2,0.2,0.0,0.2,0.0
2,NaN,NaT,NaN,None,None,NaN,TyTy Washington Jr.,NaN,1610612749,1631102,...,0.0,0.0000,0.0,0.4,0.4,1.6,0.6,0.0,0.2,0.0
3,NaN,NaT,NaN,None,None,NaN,AJ Green,NaN,1610612749,1631260,...,0.0,0.0000,0.0,2.4,2.4,1.4,0.0,0.2,1.0,2.6
4,NaN,NaT,NaN,None,None,NaN,Sam Hauser,NaN,1610612738,1630573,...,0.2,0.2000,0.8,2.2,3.0,0.8,1.4,0.2,0.6,2.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335013,22401229.0,2024-12-14,2024.0,0,H,1.610613e+09,Clint Capela,1.610613e+09,1610612737,203991,...,1.0,0.4000,5.0,7.2,12.2,1.4,0.6,0.8,0.4,2.6
335014,22401229.0,2024-12-14,2024.0,0,H,1.610613e+09,Taurean Prince,1.610613e+09,1610612749,1627752,...,0.4,0.2000,0.2,2.4,2.6,1.8,0.6,0.4,0.8,1.2
335015,22401229.0,2024-12-14,2024.0,0,H,1.610613e+09,Giannis Antetokounmpo,1.610613e+09,1610612749,203507,...,13.2,0.6188,1.8,7.6,9.4,3.8,0.8,1.6,4.0,1.4
335016,22401230.0,2024-12-14,2024.0,0,H,1.610613e+09,Steven Adams,1.610613e+09,1610612745,203500,...,2.0,0.3000,1.8,2.4,4.2,0.6,0.0,0.4,0.6,1.0
335017,22401229.0,2024-12-14,2024.0,0,H,1.610613e+09,Bobby Portis,1.610613e+09,1610612749,1626171,...,1.4,0.4334,1.8,6.6,8.4,2.8,1.0,0.8,1.2,1.6

In [8]:
season_games_plyrs['days_since_last_game'] = (
    season_games_plyrs.sort_values(by=['player_id', 'date'])
             .groupby('player_id')['date']
             .transform(lambda x: x.diff().dt.days.fillna(7))
)

display(season_games_plyrs)

,game_id,date,season,is_playoff,winner,home_id,player_name,away_id,team_id,player_id,...,ft_pct_avg,oreb_avg,dreb_avg,reb_avg,ast_avg,stl_avg,blk_avg,tov_avg,pf_avg,days_since_last_game
0,NaN,NaT,NaN,None,None,NaN,Andre Jackson Jr.,NaN,1610612749,1641748,...,0.0000,0.8,1.4,2.2,1.4,1.0,0.2,1.0,3.0,7.0
1,NaN,NaT,NaN,None,None,NaN,Chris Livingston,NaN,1610612749,1641753,...,0.0000,0.2,0.2,0.4,0.2,0.2,0.0,0.2,0.0,7.0
2,NaN,NaT,NaN,None,None,NaN,TyTy Washington Jr.,NaN,1610612749,1631102,...,0.0000,0.0,0.4,0.4,1.6,0.6,0.0,0.2,0.0,7.0
3,NaN,NaT,NaN,None,None,NaN,AJ Green,NaN,1610612749,1631260,...,0.0000,0.0,2.4,2.4,1.4,0.0,0.2,1.0,2.6,7.0
4,NaN,NaT,NaN,None,None,NaN,Sam Hauser,NaN,1610612738,1630573,...,0.2000,0.8,2.2,3.0,0.8,1.4,0.2,0.6,2.2,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335013,22401229.0,2024-12-14,2024.0,0,H,1.610613e+09,Clint Capela,1.610613e+09,1610612737,203991,...,0.4000,5.0,7.2,12.2,1.4,0.6,0.8,0.4,2.6,3.0
335014,22401229.0,2024-12-14,2024.0,0,H,1.610613e+09,Taurean Prince,1.610613e+09,1610612749,1627752,...,0.2000,0.2,2.4,2.6,1.8,0.6,0.4,0.8,1.2,4.0
335015,22401229.0,2024-12-14,2024.0,0,H,1.610613e+09,Giannis Antetokounmpo,1.610613e+09,1610612749,203507,...,0.6188,1.8,7.6,9.4,3.8,0.8,1.6,4.0,1.4,4.0
335016,22401230.0,2024-12-14,2024.0,0,H,1.610613e+09,Steven Adams,1.610613e+09,1610612745,203500,...,0.3000,1.8,2.4,4.2,0.6,0.0,0.4,0.6,1.0,6.0
335017,22401229.0,2024-12-14,2024.0,0,H,1.610613e+09,Bobby Portis,1.610613e+09,1610612749,1626171,...,0.4334,1.8,6.6,8.4,2.8,1.0,0.8,1.2,1.6,4.0

In [9]:
season_games_plyrs.columns

Index(['game_id', 'date', 'season', 'is_playoff', 'winner', 'home_id',
       'player_name', 'away_id', 'team_id', 'player_id', 'minutes', 'pts',
       'fgm', 'fga', 'fg_pct', 'fg3m', 'fg3a', 'fg3_pct', 'ftm', 'fta',
       'ft_pct', 'oreb', 'dreb', 'reb', 'ast', 'stl', 'blk', 'tov', 'pf',
       'plus_minus', 'pts_avg', 'fgm_avg', 'fga_avg', 'fg_pct_avg', 'fg3m_avg',
       'fg3a_avg', 'fg3_pct_avg', 'ftm_avg', 'fta_avg', 'ft_pct_avg',
       'oreb_avg', 'dreb_avg', 'reb_avg', 'ast_avg', 'stl_avg', 'blk_avg',
       'tov_avg', 'pf_avg', 'days_since_last_game'],
      dtype='object')

In [10]:
# Define the opponent_team_id column
season_games_plyrs['opponent_team_id'] = season_games_plyrs.apply(
    lambda row: row['away_id'] if row['team_id'] == row['home_id'] else row['home_id'],
    axis=1
)

# Combine home and away stats into a unified DataFrame for conceded stats
team_stats = pd.concat([
    games_df[['date', 'home_id'] + [f'away_{stat}' for stat in stats_columns]].rename(
        columns={**{'home_id': 'team_id'},
                 **{f'away_{stat}': f'{stat}_conceded' for stat in stats_columns}}
    ),
    games_df[['date', 'away_id'] + [f'home_{stat}' for stat in stats_columns]].rename(
        columns={**{'away_id': 'team_id'},
                 **{f'home_{stat}': f'{stat}_conceded' for stat in stats_columns}}
    )
], ignore_index=True)

# Sort by team_id and date
team_stats = team_stats.sort_values(by=['team_id', 'date'])

# Calculate rolling averages for stats conceded by each team
for stat in stats_columns:
    conceded_stat = f'{stat}_conceded'
    rolling_stat = f'rolling_avg_{conceded_stat}'
    team_stats[rolling_stat] = (
        team_stats.groupby('team_id')[conceded_stat]
        .transform(lambda x: x.shift(1).rolling(window=10, min_periods=1).mean())
    )

# Map opponent stats back to the players DataFrame
# First, merge opponent stats into the players DataFrame using opponent_team_id
rolling_columns = [f'rolling_avg_{stat}_conceded' for stat in stats_columns]
season_games_plyrs = season_games_plyrs.merge(
    team_stats[['team_id', 'date'] + rolling_columns],
    left_on=['opponent_team_id', 'date'],  # Match on opponent and game date
    right_on=['team_id', 'date'],  # Match on team_id and date
    how='left'
)

# Rename columns dynamically for clarity
renamed_columns = {
    f'rolling_avg_{stat}_conceded': f'opponent_avg_conceded_{stat}' for stat in stats_columns
}
season_games_plyrs.rename(columns=renamed_columns, inplace=True)

# Check the final result
display(season_games_plyrs)

,game_id,date,season,is_playoff,winner,home_id,player_name,away_id,team_id_x,player_id,...,opponent_avg_conceded_fta,opponent_avg_conceded_ft_pct,opponent_avg_conceded_oreb,opponent_avg_conceded_dreb,opponent_avg_conceded_reb,opponent_avg_conceded_ast,opponent_avg_conceded_stl,opponent_avg_conceded_blk,opponent_avg_conceded_tov,opponent_avg_conceded_pf
0,NaN,NaT,NaN,None,None,NaN,Andre Jackson Jr.,NaN,1610612749,1641748,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaT,NaN,None,None,NaN,Chris Livingston,NaN,1610612749,1641753,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaT,NaN,None,None,NaN,TyTy Washington Jr.,NaN,1610612749,1631102,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaT,NaN,None,None,NaN,AJ Green,NaN,1610612749,1631260,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaT,NaN,None,None,NaN,Sam Hauser,NaN,1610612738,1630573,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335013,22401229.0,2024-12-14,2024.0,0,H,1.610613e+09,Clint Capela,1.610613e+09,1610612737,203991,...,21.2,0.8550,10.7,31.1,41.8,24.8,8.9,4.1,12.5,21.1
335014,22401229.0,2024-12-14,2024.0,0,H,1.610613e+09,Taurean Prince,1.610613e+09,1610612749,1627752,...,21.4,0.7672,10.4,33.0,43.4,28.2,9.7,6.4,16.2,19.6
335015,22401229.0,2024-12-14,2024.0,0,H,1.610613e+09,Giannis Antetokounmpo,1.610613e+09,1610612749,203507,...,21.4,0.7672,10.4,33.0,43.4,28.2,9.7,6.4,16.2,19.6
335016,22401230.0,2024-12-14,2024.0,0,H,1.610613e+09,Steven Adams,1.610613e+09,1610612745,203500,...,23.9,0.7504,11.2,33.5,44.7,23.9,6.8,5.5,18.6,17.7
335017,22401229.0,2024-12-14,2024.0,0,H,1.610613e+09,Bobby Portis,1.610613e+09,1610612749,1626171,...,21.4,0.7672,10.4,33.0,43.4,28.2,9.7,6.4,16.2,19.6

In [11]:
for col in season_games_plyrs.columns:
    print(col)

game_id
date
season
is_playoff
winner
home_id
player_name
away_id
team_id_x
player_id
minutes
pts
fgm
fga
fg_pct
fg3m
fg3a
fg3_pct
ftm
fta
ft_pct
oreb
dreb
reb
ast
stl
blk
tov
pf
plus_minus
pts_avg
fgm_avg
fga_avg
fg_pct_avg
fg3m_avg
fg3a_avg
fg3_pct_avg
ftm_avg
fta_avg
ft_pct_avg
oreb_avg
dreb_avg
reb_avg
ast_avg
stl_avg
blk_avg
tov_avg
pf_avg
days_since_last_game
opponent_team_id
team_id_y
opponent_avg_conceded_pts
opponent_avg_conceded_fgm
opponent_avg_conceded_fga
opponent_avg_conceded_fg_pct
opponent_avg_conceded_fg3m
opponent_avg_conceded_fg3a
opponent_avg_conceded_fg3_pct
opponent_avg_conceded_ftm
opponent_avg_conceded_fta
opponent_avg_conceded_ft_pct
opponent_avg_conceded_oreb
opponent_avg_conceded_dreb
opponent_avg_conceded_reb
opponent_avg_conceded_ast
opponent_avg_conceded_stl
opponent_avg_conceded_blk
opponent_avg_conceded_tov
opponent_avg_conceded_pf

In [20]:
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.linear_model import LinearRegression
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Split the dataset into training and testing based on the season
train_data = season_games_plyrs[season_games_plyrs['season'] < 2024]
test_data = season_games_plyrs[season_games_plyrs['season'] == 2024]

# Define feature columns (excluding target stats)
selected_stat = "pts"
additional_stats = ["fg_pct"]
feature_columns = [f"{selected_stat}_avg", f"opponent_avg_conceded_{selected_stat}", "days_since_last_game"]

for add_stat in additional_stats:
    feature_columns.extend([f"{add_stat}_avg", f"opponent_avg_conceded_{add_stat}"])

print("Feature columns:", feature_columns)

# Drop rows with NaN values in feature columns for training and testing
X_train = train_data[feature_columns].dropna()
y_train = train_data.loc[X_train.index, selected_stat]  # Align target with filtered features
X_test = test_data[feature_columns].dropna()
y_test = test_data.loc[X_test.index, selected_stat]  # Align target with filtered features

# Define models to compare
models = {
    "RandomForest": RandomForestRegressor(random_state=42, n_estimators=100),
    "GradientBoosting": GradientBoostingRegressor(random_state=42, n_estimators=100),
    "LinearRegression": LinearRegression(),
    "XGBoost": XGBRegressor(random_state=42, n_estimators=100, use_label_encoder=False, eval_metric='rmse')
}

# Train and evaluate each model
results = {}

best_model_result = 1000
best_model = None

for name, model in models.items():
    print(f"Training {name} model...")
    
    # Train the model
    model.fit(X_train, y_train)
    
    # Predict and evaluate
    y_pred = model.predict(X_test)
    mse_result = mean_squared_error(y_test, y_pred)
    mae_result = mean_absolute_error(y_test, y_pred)
    
    # Store results
    results[name] = {'mse': mse_result, 'mae': mae_result, 'y_test': y_test, 'y_pred': y_pred, 'model': model, "model_name": name}
    
    # Display results
    print(f"{name} - Test MSE: {mse_result:.4f}, Test MAE: {mae_result:.4f}")

    if mae_result < best_model_result:
        best_model_result = mae_result
        best_model = results[name]

Feature columns: ['pts_avg', 'opponent_avg_conceded_pts', 'days_since_last_game', 'fg_pct_avg', 'opponent_avg_conceded_fg_pct']
Training RandomForest model...
RandomForest - Test MSE: 41.0193, Test MAE: 4.9523
Training GradientBoosting model...
GradientBoosting - Test MSE: 38.1195, Test MAE: 4.7774
Training LinearRegression model...
LinearRegression - Test MSE: 38.6152, Test MAE: 4.8177
Training XGBoost model...

C:\Users\caiog\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\xgboost\core.py:158: UserWarning: [16:03:46] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

XGBoost - Test MSE: 38.5544, Test MAE: 4.8065

In [21]:
results_df = pd.DataFrame({
    'Actual': best_model['y_test'].values,
    'Predicted': best_model['y_pred']
})

results_df["Difference"] = results_df.apply(lambda x: x["Actual"] - x["Predicted"], axis=1)
results_df["Negative Diff"] = results_df["Difference"] > 0

display(results_df)

total_pos_diff = results_df["Negative Diff"].sum()
print("Positive difference:", total_pos_diff/len(results_df))

      Actual  Predicted  Difference  Negative Diff
0         18  11.527761    6.472239           True
1         36  23.524933   12.475067           True
2          0   3.492794   -3.492794          False
3          0   2.840560   -2.840560          False
4          2   2.433889   -0.433889          False
...      ...        ...         ...            ...
7782       6   7.727139   -1.727139          False
7783       6   5.449743    0.550257           True
7784      32  28.886595    3.113405           True
7785       4   2.936290    1.063710           True
7786      10  13.230830   -3.230830          False

[7787 rows x 4 columns]

Positive difference: 0.44741235392320533

In [24]:
# Define confidence interval based on historical model error
confidence_margin = best_model['mae']  # Example: based on standard deviation or MAE of past predictions

# Calculate theoretical bounds
results_df['Lower_Bound'] = results_df['Predicted'] - confidence_margin
results_df['Upper_Bound'] = results_df['Predicted'] + confidence_margin

# Simulate betting strategy
def betting_decision(row, theoretical_line):
    if theoretical_line > row['Upper_Bound']:
        return 'Bet Under'
    elif theoretical_line < row['Lower_Bound']:
        return 'Bet Over'
    else:
        return 'No Bet'

# Apply betting decisions for future games
theoretical_line = 25  # Example: set a constant or dynamic theoretical line
results_df['Bet_Suggestion'] = results_df.apply(lambda row: betting_decision(row, theoretical_line), axis=1)

# Display results
print(results_df[['Actual', 'Predicted', 'Difference', 'Lower_Bound', 'Upper_Bound', 'Bet_Suggestion']])

      Actual  Predicted  Difference  Lower_Bound  Upper_Bound Bet_Suggestion
0         18  11.527761    6.472239     6.750318    16.305203      Bet Under
1         36  23.524933   12.475067    18.747491    28.302376         No Bet
2          0   3.492794   -3.492794    -1.284648     8.270237      Bet Under
3          0   2.840560   -2.840560    -1.936882     7.618003      Bet Under
4          2   2.433889   -0.433889    -2.343554     7.211331      Bet Under
...      ...        ...         ...          ...          ...            ...
7782       6   7.727139   -1.727139     2.949697    12.504582      Bet Under
7783       6   5.449743    0.550257     0.672301    10.227186      Bet Under
7784      32  28.886595    3.113405    24.109153    33.664037         No Bet
7785       4   2.936290    1.063710    -1.841152     7.713733      Bet Under
7786      10  13.230830   -3.230830     8.453388    18.008273      Bet Under

[7787 rows x 6 columns]

In [25]:
if save_pipeline:
    path = f"../dist/betting"

    model_dict = {
        "model": best_model['model'],
        "confidence_margin": confidence_margin,
    }
    
    save_file(path, model, f"{selected_stat}")