In [1]:
import pandas as pd

from helpers.file import save_file
from helpers import regression as rh
from services.mysql import MySQLService

In [ ]:
save_pipeline = False
random_state = 0
season = 2024

In [19]:
mysql = MySQLService()

order_by_clause = "date ASC"
games_df = mysql.get_data("games", order_by_clause=order_by_clause)

season_games_plyrs = mysql.execute_query(f"""
    SELECT g.id as game_id, g.date, g.season, g.is_playoff, g.winner, g.home_id, p.name as player_name, g.away_id, pg.team_id, pg.player_id, pg.minutes, pg.pts, pg.fgm, pg.fga, pg.fg_pct, pg.fg3m, pg.fg3a, pg.fg3_pct, pg.ftm, pg.fta, pg.ft_pct, pg.oreb, pg.dreb, pg.reb, pg.ast, pg.stl, pg.blk, pg.tov, pg.pf, pg.plus_minus
    FROM player_games AS pg
        LEFT JOIN games as g on pg.game_id = g.id 
        LEFT JOIN players as p on pg.player_id = p.id 
    ORDER BY g.date ASC""")

display(games_df)
display(season_games_plyrs)

c:\Users\caiog\Projects\Personal\NBA-Predictor\src\services\mysql.py:28: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  resp = pd.read_sql_query(query, db)

,id,date,season,is_playoff,winner,home_id,home_team,home_pts,home_fgm,home_fga,...,away_oreb,away_dreb,away_reb,away_ast,away_stl,away_blk,away_tov,away_pf,home_odds,away_odds
0,21200001,2012-10-30,2012,0,H,1610612739,Cleveland Cavaliers,94,36,79,...,18,21,39,26,11,10,13,19,1.41,2.93
1,21200002,2012-10-30,2012,0,H,1610612748,Miami Heat,120,43,79,...,7,34,41,24,4,2,16,23,1.35,3.26
2,21200003,2012-10-30,2012,0,A,1610612747,Los Angeles Lakers,91,38,77,...,9,31,40,22,9,5,12,25,1.21,4.54
3,21200004,2012-10-31,2012,0,A,1610612761,Toronto Raptors,88,33,91,...,9,37,46,22,3,10,19,16,2.03,1.79
4,21200005,2012-10-31,2012,0,H,1610612755,Philadelphia 76ers,84,30,85,...,16,38,54,19,9,5,22,22,2.02,1.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15820,22401218,2024-12-15,2024,0,A,1610612759,San Antonio Spurs,92,37,91,...,14,37,51,26,11,4,12,13,2.57,1.53
15821,22401219,2024-12-15,2024,0,H,1610612756,Phoenix Suns,116,43,89,...,12,36,48,30,6,4,13,22,1.17,5.32
15822,22401220,2024-12-15,2024,0,H,1610612747,Los Angeles Lakers,116,39,82,...,17,33,50,25,10,3,21,31,2.14,1.74
15823,22401227,2024-12-15,2024,0,A,1610612753,Orlando Magic,91,36,86,...,7,38,45,20,8,3,19,16,2.56,1.53
15824,22401228,2024-12-15,2024,0,A,1610612744,Golden State Warriors,133,49,103,...,10,37,47,36,8,5,16,12,1.89,1.95

,game_id,date,season,is_playoff,winner,home_id,player_name,away_id,team_id,player_id,...,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,plus_minus
0,NaN,NaT,NaN,None,None,NaN,Andre Jackson Jr.,NaN,1610612749,1641748,...,0.000,0,0,0,0,0,0,0,0,-4
1,NaN,NaT,NaN,None,None,NaN,Chris Livingston,NaN,1610612749,1641753,...,0.000,0,0,0,0,0,0,0,0,-2
2,NaN,NaT,NaN,None,None,NaN,TyTy Washington Jr.,NaN,1610612749,1631102,...,0.000,0,0,0,0,0,0,0,0,-2
3,NaN,NaT,NaN,None,None,NaN,AJ Green,NaN,1610612749,1631260,...,0.000,0,1,1,0,0,0,0,0,6
4,NaN,NaT,NaN,None,None,NaN,Sam Hauser,NaN,1610612738,1630573,...,0.000,2,3,5,2,2,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335167,22401220.0,2024-12-15,2024.0,0,H,1.610613e+09,DAngelo Russell,1.610613e+09,1610612747,1626156,...,0.500,0,3,3,2,1,0,3,1,-7
335168,22401216.0,2024-12-15,2024.0,0,H,1.610613e+09,T.J. McConnell,1.610613e+09,1610612754,204456,...,0.000,2,1,3,8,0,0,2,3,0
335169,22401227.0,2024-12-15,2024.0,0,A,1.610613e+09,Karl-Anthony Towns,1.610613e+09,1610612752,1626157,...,1.000,4,18,22,5,0,1,6,4,9
335170,22401219.0,2024-12-15,2024.0,0,H,1.610613e+09,Tyus Jones,1.610613e+09,1610612756,1626145,...,0.000,0,4,4,4,0,0,2,3,-4
335171,22401219.0,2024-12-15,2024.0,0,H,1.610613e+09,Devin Booker,1.610613e+09,1610612756,1626164,...,0.833,1,2,3,5,1,0,2,0,1

In [20]:
season_games_plyrs.columns

Index(['game_id', 'date', 'season', 'is_playoff', 'winner', 'home_id',
       'player_name', 'away_id', 'team_id', 'player_id', 'minutes', 'pts',
       'fgm', 'fga', 'fg_pct', 'fg3m', 'fg3a', 'fg3_pct', 'ftm', 'fta',
       'ft_pct', 'oreb', 'dreb', 'reb', 'ast', 'stl', 'blk', 'tov', 'pf',
       'plus_minus'],
      dtype='object')

In [21]:
stats_columns = ['pts','fgm', 'fga', 'fg_pct', 'fg3m', 'fg3a', 'fg3_pct', 'ftm', 'fta',
    'ft_pct', 'oreb', 'dreb', 'reb', 'ast', 'stl', 'blk', 'tov', 'pf']

rh.build_avg_columns(season_games_plyrs, stats_columns)

display(season_games_plyrs)

100%|██████████| 18/18 [00:11<00:00,  1.56it/s]

,game_id,date,season,is_playoff,winner,home_id,player_name,away_id,team_id,player_id,...,fta_avg,ft_pct_avg,oreb_avg,dreb_avg,reb_avg,ast_avg,stl_avg,blk_avg,tov_avg,pf_avg
0,NaN,NaT,NaN,None,None,NaN,Andre Jackson Jr.,NaN,1610612749,1641748,...,0.0,0.0000,0.8,1.4,2.2,1.4,1.0,0.2,1.0,3.0
1,NaN,NaT,NaN,None,None,NaN,Chris Livingston,NaN,1610612749,1641753,...,0.6,0.0000,0.2,0.2,0.4,0.2,0.2,0.0,0.2,0.0
2,NaN,NaT,NaN,None,None,NaN,TyTy Washington Jr.,NaN,1610612749,1631102,...,0.0,0.0000,0.0,0.4,0.4,1.6,0.6,0.0,0.2,0.0
3,NaN,NaT,NaN,None,None,NaN,AJ Green,NaN,1610612749,1631260,...,0.0,0.0000,0.0,2.4,2.4,1.4,0.0,0.2,1.0,2.6
4,NaN,NaT,NaN,None,None,NaN,Sam Hauser,NaN,1610612738,1630573,...,0.2,0.2000,1.2,2.6,3.8,0.8,1.4,0.2,0.4,1.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335167,22401220.0,2024-12-15,2024.0,0,H,1.610613e+09,DAngelo Russell,1.610613e+09,1610612747,1626156,...,1.4,0.3666,0.4,2.8,3.2,5.4,0.4,0.0,2.2,2.0
335168,22401216.0,2024-12-15,2024.0,0,H,1.610613e+09,T.J. McConnell,1.610613e+09,1610612754,204456,...,2.4,0.7334,0.4,1.4,1.8,4.2,1.4,0.6,1.6,0.8
335169,22401227.0,2024-12-15,2024.0,0,A,1.610613e+09,Karl-Anthony Towns,1.610613e+09,1610612752,1626157,...,7.0,0.8156,2.8,14.0,16.8,3.0,1.2,2.0,3.2,3.6
335170,22401219.0,2024-12-15,2024.0,0,H,1.610613e+09,Tyus Jones,1.610613e+09,1610612756,1626145,...,1.6,0.8000,0.2,1.8,2.0,6.2,1.2,0.0,0.6,1.2
335171,22401219.0,2024-12-15,2024.0,0,H,1.610613e+09,Devin Booker,1.610613e+09,1610612756,1626164,...,7.6,0.9636,1.0,3.6,4.6,5.8,1.6,0.2,3.2,3.2

In [22]:
rh.build_days_since_last_game_col(season_games_plyrs)

display(season_games_plyrs)

,game_id,date,season,is_playoff,winner,home_id,player_name,away_id,team_id,player_id,...,ft_pct_avg,oreb_avg,dreb_avg,reb_avg,ast_avg,stl_avg,blk_avg,tov_avg,pf_avg,days_since_last_game
0,NaN,NaT,NaN,None,None,NaN,Andre Jackson Jr.,NaN,1610612749,1641748,...,0.0000,0.8,1.4,2.2,1.4,1.0,0.2,1.0,3.0,7.0
1,NaN,NaT,NaN,None,None,NaN,Chris Livingston,NaN,1610612749,1641753,...,0.0000,0.2,0.2,0.4,0.2,0.2,0.0,0.2,0.0,7.0
2,NaN,NaT,NaN,None,None,NaN,TyTy Washington Jr.,NaN,1610612749,1631102,...,0.0000,0.0,0.4,0.4,1.6,0.6,0.0,0.2,0.0,7.0
3,NaN,NaT,NaN,None,None,NaN,AJ Green,NaN,1610612749,1631260,...,0.0000,0.0,2.4,2.4,1.4,0.0,0.2,1.0,2.6,7.0
4,NaN,NaT,NaN,None,None,NaN,Sam Hauser,NaN,1610612738,1630573,...,0.2000,1.2,2.6,3.8,0.8,1.4,0.2,0.4,1.8,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335167,22401220.0,2024-12-15,2024.0,0,H,1.610613e+09,DAngelo Russell,1.610613e+09,1610612747,1626156,...,0.3666,0.4,2.8,3.2,5.4,0.4,0.0,2.2,2.0,2.0
335168,22401216.0,2024-12-15,2024.0,0,H,1.610613e+09,T.J. McConnell,1.610613e+09,1610612754,204456,...,0.7334,0.4,1.4,1.8,4.2,1.4,0.6,1.6,0.8,2.0
335169,22401227.0,2024-12-15,2024.0,0,A,1.610613e+09,Karl-Anthony Towns,1.610613e+09,1610612752,1626157,...,0.8156,2.8,14.0,16.8,3.0,1.2,2.0,3.2,3.6,4.0
335170,22401219.0,2024-12-15,2024.0,0,H,1.610613e+09,Tyus Jones,1.610613e+09,1610612756,1626145,...,0.8000,0.2,1.8,2.0,6.2,1.2,0.0,0.6,1.2,2.0
335171,22401219.0,2024-12-15,2024.0,0,H,1.610613e+09,Devin Booker,1.610613e+09,1610612756,1626164,...,0.9636,1.0,3.6,4.6,5.8,1.6,0.2,3.2,3.2,2.0

In [23]:
season_games_plyrs.columns

Index(['game_id', 'date', 'season', 'is_playoff', 'winner', 'home_id',
       'player_name', 'away_id', 'team_id', 'player_id', 'minutes', 'pts',
       'fgm', 'fga', 'fg_pct', 'fg3m', 'fg3a', 'fg3_pct', 'ftm', 'fta',
       'ft_pct', 'oreb', 'dreb', 'reb', 'ast', 'stl', 'blk', 'tov', 'pf',
       'plus_minus', 'pts_avg', 'fgm_avg', 'fga_avg', 'fg_pct_avg', 'fg3m_avg',
       'fg3a_avg', 'fg3_pct_avg', 'ftm_avg', 'fta_avg', 'ft_pct_avg',
       'oreb_avg', 'dreb_avg', 'reb_avg', 'ast_avg', 'stl_avg', 'blk_avg',
       'tov_avg', 'pf_avg', 'days_since_last_game'],
      dtype='object')

In [24]:
season_games_plyrs = rh.build_opponent_conceded_columns(season_games_plyrs, games_df, stats_columns)

# Check the final result
display(season_games_plyrs)

,game_id,date,season,is_playoff,winner,home_id,player_name,away_id,team_id_x,player_id,...,opponent_avg_conceded_fta,opponent_avg_conceded_ft_pct,opponent_avg_conceded_oreb,opponent_avg_conceded_dreb,opponent_avg_conceded_reb,opponent_avg_conceded_ast,opponent_avg_conceded_stl,opponent_avg_conceded_blk,opponent_avg_conceded_tov,opponent_avg_conceded_pf
0,NaN,NaT,NaN,None,None,NaN,Andre Jackson Jr.,NaN,1610612749,1641748,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaT,NaN,None,None,NaN,Chris Livingston,NaN,1610612749,1641753,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaT,NaN,None,None,NaN,TyTy Washington Jr.,NaN,1610612749,1631102,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaT,NaN,None,None,NaN,AJ Green,NaN,1610612749,1631260,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaT,NaN,None,None,NaN,Sam Hauser,NaN,1610612738,1630573,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335167,22401220.0,2024-12-15,2024.0,0,H,1.610613e+09,DAngelo Russell,1.610613e+09,1610612747,1626156,...,26.9,0.7767,12.9,31.8,44.7,23.8,8.1,5.7,16.2,19.8
335168,22401216.0,2024-12-15,2024.0,0,H,1.610613e+09,T.J. McConnell,1.610613e+09,1610612754,204456,...,21.7,0.7634,12.5,37.8,50.3,30.1,9.9,4.8,16.0,17.8
335169,22401227.0,2024-12-15,2024.0,0,A,1.610613e+09,Karl-Anthony Towns,1.610613e+09,1610612752,1626157,...,21.7,0.7596,8.2,29.6,37.8,22.8,7.9,4.4,18.5,22.3
335170,22401219.0,2024-12-15,2024.0,0,H,1.610613e+09,Tyus Jones,1.610613e+09,1610612756,1626145,...,25.1,0.7902,12.4,32.8,45.2,28.8,9.2,6.9,14.5,17.8
335171,22401219.0,2024-12-15,2024.0,0,H,1.610613e+09,Devin Booker,1.610613e+09,1610612756,1626164,...,25.1,0.7902,12.4,32.8,45.2,28.8,9.2,6.9,14.5,17.8

In [25]:
for col in season_games_plyrs.columns:
    print(col)

game_id
date
season
is_playoff
winner
home_id
player_name
away_id
team_id_x
player_id
minutes
pts
fgm
fga
fg_pct
fg3m
fg3a
fg3_pct
ftm
fta
ft_pct
oreb
dreb
reb
ast
stl
blk
tov
pf
plus_minus
pts_avg
fgm_avg
fga_avg
fg_pct_avg
fg3m_avg
fg3a_avg
fg3_pct_avg
ftm_avg
fta_avg
ft_pct_avg
oreb_avg
dreb_avg
reb_avg
ast_avg
stl_avg
blk_avg
tov_avg
pf_avg
days_since_last_game
opponent_team_id
team_id_y
opponent_avg_conceded_pts
opponent_avg_conceded_fgm
opponent_avg_conceded_fga
opponent_avg_conceded_fg_pct
opponent_avg_conceded_fg3m
opponent_avg_conceded_fg3a
opponent_avg_conceded_fg3_pct
opponent_avg_conceded_ftm
opponent_avg_conceded_fta
opponent_avg_conceded_ft_pct
opponent_avg_conceded_oreb
opponent_avg_conceded_dreb
opponent_avg_conceded_reb
opponent_avg_conceded_ast
opponent_avg_conceded_stl
opponent_avg_conceded_blk
opponent_avg_conceded_tov
opponent_avg_conceded_pf

In [ ]:
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.linear_model import LinearRegression
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Split the dataset into training and testing based on the season
train_data = season_games_plyrs[season_games_plyrs['season'] < season]
test_data = season_games_plyrs[season_games_plyrs['season'] == season]

# Define feature columns (excluding target stats)
selected_stat = "pts"
additional_stats = ["fg_pct", "fg3_pct"]
feature_columns = [f"{selected_stat}_avg", f"opponent_avg_conceded_{selected_stat}", "days_since_last_game"]

for add_stat in additional_stats:
    feature_columns.extend([f"{add_stat}_avg", f"opponent_avg_conceded_{add_stat}"])

print("Feature columns:", feature_columns)

# Drop rows with NaN values in feature columns for training and testing
X_train = train_data[feature_columns].dropna()
y_train = train_data.loc[X_train.index, selected_stat]  # Align target with filtered features
X_test = test_data[feature_columns].dropna()
y_test = test_data.loc[X_test.index, selected_stat]  # Align target with filtered features

# Define models to compare
models = {
    "RandomForest": RandomForestRegressor(random_state=random_state, n_estimators=100),
    "GradientBoosting": GradientBoostingRegressor(random_state=random_state, n_estimators=100),
    "LinearRegression": LinearRegression(),
    "XGBoost": XGBRegressor(random_state=random_state, n_estimators=100, use_label_encoder=False, eval_metric='rmse')
}

# Train and evaluate each model
results = {}

best_model_result = 1000
best_model = None

for name, model in models.items():
    print(f"Training {name} model...")
    
    # Train the model
    model.fit(X_train, y_train)
    
    # Predict and evaluate
    y_pred = model.predict(X_test)
    mse_result = mean_squared_error(y_test, y_pred)
    mae_result = mean_absolute_error(y_test, y_pred)
    
    # Store results
    results[name] = {'mse': mse_result, 'mae': mae_result, 'y_test': y_test, 'y_pred': y_pred, 'model': model, "model_name": name}
    
    # Display results
    print(f"{name} - Test MSE: {mse_result:.4f}, Test MAE: {mae_result:.4f}")

    if mae_result < best_model_result:
        best_model_result = mae_result
        best_model = results[name]

Feature columns: ['pts_avg', 'opponent_avg_conceded_pts', 'days_since_last_game', 'fg_pct_avg', 'opponent_avg_conceded_fg_pct', 'fg3_pct_avg', 'opponent_avg_conceded_fg3_pct']
Training RandomForest model...
RandomForest - Test MSE: 39.6841, Test MAE: 4.8800
Training GradientBoosting model...
GradientBoosting - Test MSE: 37.7935, Test MAE: 4.7498
Training LinearRegression model...
LinearRegression - Test MSE: 38.3389, Test MAE: 4.7949
Training XGBoost model...

C:\Users\caiog\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\xgboost\core.py:158: UserWarning: [11:02:26] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

XGBoost - Test MSE: 38.2112, Test MAE: 4.7788

In [27]:
results_df = pd.DataFrame({
    'Actual': best_model['y_test'].values,
    'Predicted': best_model['y_pred']
})

results_df["Difference"] = results_df.apply(lambda x: x["Actual"] - x["Predicted"], axis=1)
results_df["Negative Diff"] = results_df["Difference"] > 0

display(results_df)

total_pos_diff = results_df["Negative Diff"].sum()
print("Positive difference:", total_pos_diff/len(results_df))

      Actual  Predicted  Difference  Negative Diff
0         18  11.129279    6.870721           True
1         36  24.031472   11.968528           True
2          0   3.347657   -3.347657          False
3          0   3.097017   -3.097017          False
4          2   2.500939   -0.500939          False
...      ...        ...         ...            ...
7936       7  13.856843   -6.856843          False
7937       6  16.474953  -10.474953          False
7938      22  19.526377    2.473623           True
7939      19  14.253062    4.746938           True
7940      28  27.523237    0.476763           True

[7941 rows x 4 columns]

Positive difference: 0.4461654703437854

In [28]:
# Define confidence interval based on historical model error
confidence_margin = best_model['mae']  # Example: based on standard deviation or MAE of past predictions

# Calculate theoretical bounds
results_df['Lower_Bound'] = results_df['Predicted'] - confidence_margin
results_df['Upper_Bound'] = results_df['Predicted'] + confidence_margin

# Simulate betting strategy
def betting_decision(row, theoretical_line):
    if theoretical_line > row['Upper_Bound']:
        return 'Bet Under'
    elif theoretical_line < row['Lower_Bound']:
        return 'Bet Over'
    else:
        return 'No Bet'

# Apply betting decisions for future games
theoretical_line = 25  # Example: set a constant or dynamic theoretical line
results_df['Bet_Suggestion'] = results_df.apply(lambda row: betting_decision(row, theoretical_line), axis=1)

# Display results
print(results_df[['Actual', 'Predicted', 'Difference', 'Lower_Bound', 'Upper_Bound', 'Bet_Suggestion']])

      Actual  Predicted  Difference  Lower_Bound  Upper_Bound Bet_Suggestion
0         18  11.129279    6.870721     6.379463    15.879095      Bet Under
1         36  24.031472   11.968528    19.281656    28.781288         No Bet
2          0   3.347657   -3.347657    -1.402159     8.097473      Bet Under
3          0   3.097017   -3.097017    -1.652799     7.846833      Bet Under
4          2   2.500939   -0.500939    -2.248877     7.250754      Bet Under
...      ...        ...         ...          ...          ...            ...
7936       7  13.856843   -6.856843     9.107027    18.606659      Bet Under
7937       6  16.474953  -10.474953    11.725137    21.224769      Bet Under
7938      22  19.526377    2.473623    14.776561    24.276193      Bet Under
7939      19  14.253062    4.746938     9.503246    19.002877      Bet Under
7940      28  27.523237    0.476763    22.773421    32.273053         No Bet

[7941 rows x 6 columns]

In [31]:
if save_pipeline:
    path = f"../dist/betting"

    model_dict = {
        "model": best_model['model'],
        "name": best_model["model_name"],
        'features': feature_columns,
        "stats_columns": stats_columns,
        "confidence_margin": confidence_margin,
    }
    
    save_file(path, model_dict, f"{selected_stat}")