In [96]:
from tqdm import tqdm
import pandas as pd

from helpers.file import save_file
from services.mysql import MySQLService

In [ ]:
save_pipeline = False

In [48]:
mysql = MySQLService()

order_by_clause = "date ASC"
games_df = mysql.get_data("games", order_by_clause=order_by_clause)

season_games_plyrs = mysql.execute_query(f"""
    SELECT g.id as game_id, g.date, g.season, g.is_playoff, g.winner, g.home_id, p.name as player_name, g.away_id, pg.team_id, pg.player_id, pg.minutes, pg.pts, pg.fgm, pg.fga, pg.fg_pct, pg.fg3m, pg.fg3a, pg.fg3_pct, pg.ftm, pg.fta, pg.ft_pct, pg.oreb, pg.dreb, pg.reb, pg.ast, pg.stl, pg.blk, pg.tov, pg.pf, pg.plus_minus
    FROM player_games AS pg
        LEFT JOIN games as g on pg.game_id = g.id 
        LEFT JOIN players as p on pg.player_id = p.id 
    ORDER BY g.date ASC""")

display(games_df)
display(season_games_plyrs)

c:\Users\caiog\Projects\Personal\NBA-Predictor\src\services\mysql.py:28: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  resp = pd.read_sql_query(query, db)

,id,date,season,is_playoff,winner,home_id,home_team,home_pts,home_fgm,home_fga,...,away_oreb,away_dreb,away_reb,away_ast,away_stl,away_blk,away_tov,away_pf,home_odds,away_odds
0,21200001,2012-10-30,2012,0,H,1610612739,Cleveland Cavaliers,94,36,79,...,18,21,39,26,11,10,13,19,1.41,2.93
1,21200002,2012-10-30,2012,0,H,1610612748,Miami Heat,120,43,79,...,7,34,41,24,4,2,16,23,1.35,3.26
2,21200003,2012-10-30,2012,0,A,1610612747,Los Angeles Lakers,91,38,77,...,9,31,40,22,9,5,12,25,1.21,4.54
3,21200004,2012-10-31,2012,0,A,1610612761,Toronto Raptors,88,33,91,...,9,37,46,22,3,10,19,16,2.03,1.79
4,21200005,2012-10-31,2012,0,H,1610612755,Philadelphia 76ers,84,30,85,...,16,38,54,19,9,5,22,22,2.02,1.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15735,22400305,2024-12-01,2024,0,A,1610612751,Brooklyn Nets,92,30,79,...,14,38,52,23,10,11,22,29,3.15,1.38
15736,22400306,2024-12-01,2024,0,H,1610612763,Memphis Grizzlies,136,49,93,...,6,35,41,28,8,3,15,22,1.43,2.88
15737,22400307,2024-12-01,2024,0,H,1610612739,Cleveland Cavaliers,115,39,80,...,10,36,46,17,11,6,12,19,1.84,2.0
15738,22400308,2024-12-01,2024,0,H,1610612752,New York Knicks,118,42,92,...,13,29,42,20,14,9,14,19,1.13,6.16
15739,22400309,2024-12-01,2024,0,H,1610612761,Toronto Raptors,119,47,88,...,12,33,45,25,11,4,14,17,2.61,1.51

,game_id,date,season,is_playoff,winner,home_id,player_name,away_id,team_id,player_id,...,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,plus_minus
0,NaN,NaT,NaN,None,None,NaN,Andre Jackson Jr.,NaN,1610612749,1641748,...,0.0,0,0,0,0,0,0,0,0,-4
1,NaN,NaT,NaN,None,None,NaN,Chris Livingston,NaN,1610612749,1641753,...,0.0,0,0,0,0,0,0,0,0,-2
2,NaN,NaT,NaN,None,None,NaN,Dillon Jones,NaN,1610612760,1641794,...,1.0,0,2,2,1,0,0,0,0,8
3,NaN,NaT,NaN,None,None,NaN,Dalton Knecht,NaN,1610612747,1642261,...,0.0,2,4,6,1,1,0,0,3,-9
4,NaN,NaT,NaN,None,None,NaN,Reed Sheppard,NaN,1610612745,1642263,...,1.0,0,0,0,0,1,0,0,1,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
333432,22400305.0,2024-12-01,2024.0,0,A,1.610613e+09,Kentavious Caldwell-Pope,1.610613e+09,1610612753,203484,...,0.0,0,1,1,0,2,1,0,2,14
333433,22400305.0,2024-12-01,2024.0,0,A,1.610613e+09,Dennis Schröder,1.610613e+09,1610612751,203471,...,1.0,0,2,2,7,1,1,6,3,-6
333434,22400308.0,2024-12-01,2024.0,0,H,1.610613e+09,CJ McCollum,1.610613e+09,1610612740,203468,...,1.0,1,2,3,3,1,0,0,2,-22
333435,22400309.0,2024-12-01,2024.0,0,H,1.610613e+09,Terry Rozier,1.610613e+09,1610612748,1626179,...,1.0,0,1,1,5,0,0,1,2,-3
333436,22400305.0,2024-12-01,2024.0,0,A,1.610613e+09,Ben Simmons,1.610613e+09,1610612751,1627732,...,0.0,1,1,2,5,1,0,1,3,1

In [49]:
season_games_plyrs.columns

Index(['game_id', 'date', 'season', 'is_playoff', 'winner', 'home_id',
       'player_name', 'away_id', 'team_id', 'player_id', 'minutes', 'pts',
       'fgm', 'fga', 'fg_pct', 'fg3m', 'fg3a', 'fg3_pct', 'ftm', 'fta',
       'ft_pct', 'oreb', 'dreb', 'reb', 'ast', 'stl', 'blk', 'tov', 'pf',
       'plus_minus'],
      dtype='object')

In [50]:
games_df.to_csv("games.csv", index=False)
season_games_plyrs.to_csv("players.csv", index=False)

In [51]:
# def get_player_rolling_avg_by_stat(game_date, stat):
#     filtered = season_games_plyrs[season_games_plyrs["date"] < game_date].iloc[:10]
#     if len(filtered) < 10:
#         return None
    
#     stat_mean = filtered[stat].mean()
#     return stat_mean

stats_columns = ['pts','fgm', 'fga', 'fg_pct', 'fg3m', 'fg3a', 'fg3_pct', 'ftm', 'fta',
    'ft_pct', 'oreb', 'dreb', 'reb', 'ast', 'stl', 'blk', 'tov', 'pf']

for i in tqdm(range(len(stats_columns))):
    stat = stats_columns[i]
    season_games_plyrs[f'{stat}_avg'] = (
        season_games_plyrs.sort_values(by=['player_id', 'date'])
                .groupby('player_id')[stat]
                .transform(lambda x: x.shift(1).rolling(window=5).mean())
    )

display(season_games_plyrs)

100%|██████████| 18/18 [00:11<00:00,  1.58it/s]

,game_id,date,season,is_playoff,winner,home_id,player_name,away_id,team_id,player_id,...,fta_avg,ft_pct_avg,oreb_avg,dreb_avg,reb_avg,ast_avg,stl_avg,blk_avg,tov_avg,pf_avg
0,NaN,NaT,NaN,None,None,NaN,Andre Jackson Jr.,NaN,1610612749,1641748,...,0.0,0.0000,2.2,4.6,6.8,1.4,0.6,0.4,1.8,2.4
1,NaN,NaT,NaN,None,None,NaN,Chris Livingston,NaN,1610612749,1641753,...,0.6,0.0000,0.4,1.0,1.4,0.0,0.0,0.0,0.2,0.6
2,NaN,NaT,NaN,None,None,NaN,Dillon Jones,NaN,1610612760,1641794,...,0.0,0.0000,0.6,1.8,2.4,0.6,0.0,0.0,0.2,0.6
3,NaN,NaT,NaN,None,None,NaN,Dalton Knecht,NaN,1610612747,1642261,...,1.0,0.3334,0.6,4.8,5.4,1.4,0.4,0.0,0.2,1.6
4,NaN,NaT,NaN,None,None,NaN,Reed Sheppard,NaN,1610612745,1642263,...,0.0,0.0000,0.2,0.4,0.6,1.4,1.2,0.4,0.8,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
333432,22400305.0,2024-12-01,2024.0,0,A,1.610613e+09,Kentavious Caldwell-Pope,1.610613e+09,1610612753,203484,...,1.2,0.7000,0.6,1.2,1.8,2.0,1.8,0.8,0.6,1.6
333433,22400305.0,2024-12-01,2024.0,0,A,1.610613e+09,Dennis Schröder,1.610613e+09,1610612751,203471,...,4.8,0.9200,0.4,3.2,3.6,7.0,0.8,0.6,2.6,2.2
333434,22400308.0,2024-12-01,2024.0,0,H,1.610613e+09,CJ McCollum,1.610613e+09,1610612740,203468,...,3.8,0.5250,0.8,3.4,4.2,3.0,1.0,0.4,2.4,1.8
333435,22400309.0,2024-12-01,2024.0,0,H,1.610613e+09,Terry Rozier,1.610613e+09,1610612748,1626179,...,1.2,0.5000,1.2,1.4,2.6,1.6,0.2,0.4,1.4,1.6
333436,22400305.0,2024-12-01,2024.0,0,A,1.610613e+09,Ben Simmons,1.610613e+09,1610612751,1627732,...,0.4,0.0000,1.4,5.0,6.4,6.0,0.8,0.6,2.4,2.0

In [52]:
season_games_plyrs['days_since_last_game'] = (
    season_games_plyrs.sort_values(by=['player_id', 'date'])
             .groupby('player_id')['date']
             .transform(lambda x: x.diff().dt.days.fillna(7))
)

display(season_games_plyrs)

,game_id,date,season,is_playoff,winner,home_id,player_name,away_id,team_id,player_id,...,ft_pct_avg,oreb_avg,dreb_avg,reb_avg,ast_avg,stl_avg,blk_avg,tov_avg,pf_avg,days_since_last_game
0,NaN,NaT,NaN,None,None,NaN,Andre Jackson Jr.,NaN,1610612749,1641748,...,0.0000,2.2,4.6,6.8,1.4,0.6,0.4,1.8,2.4,7.0
1,NaN,NaT,NaN,None,None,NaN,Chris Livingston,NaN,1610612749,1641753,...,0.0000,0.4,1.0,1.4,0.0,0.0,0.0,0.2,0.6,7.0
2,NaN,NaT,NaN,None,None,NaN,Dillon Jones,NaN,1610612760,1641794,...,0.0000,0.6,1.8,2.4,0.6,0.0,0.0,0.2,0.6,7.0
3,NaN,NaT,NaN,None,None,NaN,Dalton Knecht,NaN,1610612747,1642261,...,0.3334,0.6,4.8,5.4,1.4,0.4,0.0,0.2,1.6,7.0
4,NaN,NaT,NaN,None,None,NaN,Reed Sheppard,NaN,1610612745,1642263,...,0.0000,0.2,0.4,0.6,1.4,1.2,0.4,0.8,1.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
333432,22400305.0,2024-12-01,2024.0,0,A,1.610613e+09,Kentavious Caldwell-Pope,1.610613e+09,1610612753,203484,...,0.7000,0.6,1.2,1.8,2.0,1.8,0.8,0.6,1.6,2.0
333433,22400305.0,2024-12-01,2024.0,0,A,1.610613e+09,Dennis Schröder,1.610613e+09,1610612751,203471,...,0.9200,0.4,3.2,3.6,7.0,0.8,0.6,2.6,2.2,4.0
333434,22400308.0,2024-12-01,2024.0,0,H,1.610613e+09,CJ McCollum,1.610613e+09,1610612740,203468,...,0.5250,0.8,3.4,4.2,3.0,1.0,0.4,2.4,1.8,2.0
333435,22400309.0,2024-12-01,2024.0,0,H,1.610613e+09,Terry Rozier,1.610613e+09,1610612748,1626179,...,0.5000,1.2,1.4,2.6,1.6,0.2,0.4,1.4,1.6,2.0
333436,22400305.0,2024-12-01,2024.0,0,A,1.610613e+09,Ben Simmons,1.610613e+09,1610612751,1627732,...,0.0000,1.4,5.0,6.4,6.0,0.8,0.6,2.4,2.0,2.0

In [53]:
season_games_plyrs.columns

Index(['game_id', 'date', 'season', 'is_playoff', 'winner', 'home_id',
       'player_name', 'away_id', 'team_id', 'player_id', 'minutes', 'pts',
       'fgm', 'fga', 'fg_pct', 'fg3m', 'fg3a', 'fg3_pct', 'ftm', 'fta',
       'ft_pct', 'oreb', 'dreb', 'reb', 'ast', 'stl', 'blk', 'tov', 'pf',
       'plus_minus', 'pts_avg', 'fgm_avg', 'fga_avg', 'fg_pct_avg', 'fg3m_avg',
       'fg3a_avg', 'fg3_pct_avg', 'ftm_avg', 'fta_avg', 'ft_pct_avg',
       'oreb_avg', 'dreb_avg', 'reb_avg', 'ast_avg', 'stl_avg', 'blk_avg',
       'tov_avg', 'pf_avg', 'days_since_last_game'],
      dtype='object')

In [56]:
# Define the opponent_team_id column
season_games_plyrs['opponent_team_id'] = season_games_plyrs.apply(
    lambda row: row['away_id'] if row['team_id'] == row['home_id'] else row['home_id'],
    axis=1
)

# Combine home and away stats into a unified DataFrame for conceded stats
team_stats = pd.concat([
    games_df[['date', 'home_id'] + [f'away_{stat}' for stat in stats_columns]].rename(
        columns={**{'home_id': 'team_id'},
                 **{f'away_{stat}': f'{stat}_conceded' for stat in stats_columns}}
    ),
    games_df[['date', 'away_id'] + [f'home_{stat}' for stat in stats_columns]].rename(
        columns={**{'away_id': 'team_id'},
                 **{f'home_{stat}': f'{stat}_conceded' for stat in stats_columns}}
    )
], ignore_index=True)

# Sort by team_id and date
team_stats = team_stats.sort_values(by=['team_id', 'date'])

# Calculate rolling averages for stats conceded by each team
for stat in stats_columns:
    conceded_stat = f'{stat}_conceded'
    rolling_stat = f'rolling_avg_{conceded_stat}'
    team_stats[rolling_stat] = (
        team_stats.groupby('team_id')[conceded_stat]
        .transform(lambda x: x.shift(1).rolling(window=10, min_periods=1).mean())
    )

# Map opponent stats back to the players DataFrame
# First, merge opponent stats into the players DataFrame using opponent_team_id
rolling_columns = [f'rolling_avg_{stat}_conceded' for stat in stats_columns]
season_games_plyrs = season_games_plyrs.merge(
    team_stats[['team_id', 'date'] + rolling_columns],
    left_on=['opponent_team_id', 'date'],  # Match on opponent and game date
    right_on=['team_id', 'date'],  # Match on team_id and date
    how='left'
)

# Rename columns dynamically for clarity
renamed_columns = {
    f'rolling_avg_{stat}_conceded': f'opponent_avg_conceded_{stat}' for stat in stats_columns
}
season_games_plyrs.rename(columns=renamed_columns, inplace=True)

# Check the final result
display(season_games_plyrs)

,game_id,date,season,is_playoff,winner,home_id,player_name,away_id,team_id_x,player_id,...,opponent_avg_conceded_fta,opponent_avg_conceded_ft_pct,opponent_avg_conceded_oreb,opponent_avg_conceded_dreb,opponent_avg_conceded_reb,opponent_avg_conceded_ast,opponent_avg_conceded_stl,opponent_avg_conceded_blk,opponent_avg_conceded_tov,opponent_avg_conceded_pf
0,NaN,NaT,NaN,None,None,NaN,Andre Jackson Jr.,NaN,1610612749,1641748,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaT,NaN,None,None,NaN,Chris Livingston,NaN,1610612749,1641753,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaT,NaN,None,None,NaN,Dillon Jones,NaN,1610612760,1641794,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaT,NaN,None,None,NaN,Dalton Knecht,NaN,1610612747,1642261,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaT,NaN,None,None,NaN,Reed Sheppard,NaN,1610612745,1642263,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
333432,22400305.0,2024-12-01,2024.0,0,A,1.610613e+09,Kentavious Caldwell-Pope,1.610613e+09,1610612753,203484,...,22.3,0.7735,10.8,32.2,43.0,28.1,8.4,6.7,13.8,20.2
333433,22400305.0,2024-12-01,2024.0,0,A,1.610613e+09,Dennis Schröder,1.610613e+09,1610612751,203471,...,19.6,0.7425,9.6,31.5,41.1,21.3,7.3,4.5,18.7,20.6
333434,22400308.0,2024-12-01,2024.0,0,H,1.610613e+09,CJ McCollum,1.610613e+09,1610612740,203468,...,22.4,0.7919,9.9,29.5,39.4,26.6,6.6,3.9,13.2,19.4
333435,22400309.0,2024-12-01,2024.0,0,H,1.610613e+09,Terry Rozier,1.610613e+09,1610612748,1626179,...,21.0,0.7440,11.1,30.6,41.7,26.4,10.1,5.2,12.8,18.7
333436,22400305.0,2024-12-01,2024.0,0,A,1.610613e+09,Ben Simmons,1.610613e+09,1610612751,1627732,...,19.6,0.7425,9.6,31.5,41.1,21.3,7.3,4.5,18.7,20.6

In [57]:
for col in season_games_plyrs.columns:
    print(col)

game_id
date
season
is_playoff
winner
home_id
player_name
away_id
team_id_x
player_id
minutes
pts
fgm
fga
fg_pct
fg3m
fg3a
fg3_pct
ftm
fta
ft_pct
oreb
dreb
reb
ast
stl
blk
tov
pf
plus_minus
pts_avg
fgm_avg
fga_avg
fg_pct_avg
fg3m_avg
fg3a_avg
fg3_pct_avg
ftm_avg
fta_avg
ft_pct_avg
oreb_avg
dreb_avg
reb_avg
ast_avg
stl_avg
blk_avg
tov_avg
pf_avg
days_since_last_game
opponent_team_id
team_id_y
opponent_avg_conceded_pts
opponent_avg_conceded_fgm
opponent_avg_conceded_fga
opponent_avg_conceded_fg_pct
opponent_avg_conceded_fg3m
opponent_avg_conceded_fg3a
opponent_avg_conceded_fg3_pct
opponent_avg_conceded_ftm
opponent_avg_conceded_fta
opponent_avg_conceded_ft_pct
opponent_avg_conceded_oreb
opponent_avg_conceded_dreb
opponent_avg_conceded_reb
opponent_avg_conceded_ast
opponent_avg_conceded_stl
opponent_avg_conceded_blk
opponent_avg_conceded_tov
opponent_avg_conceded_pf

In [75]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Split the dataset into training and testing based on the season
train_data = season_games_plyrs[season_games_plyrs['season'] < 2024]
test_data = season_games_plyrs[season_games_plyrs['season'] == 2024]

# Define feature columns (excluding target stats)
feature_columns = [col for col in season_games_plyrs.columns 
                   if col not in stats_columns + ['player_id', 'game_id', 'date', 'team_id', 'opponent_team_id']]

# Train and evaluate a model for each stat
results = {}
selected_stat = "pts"
additional_stats = ["fg_pct"]

print(f"Training model to predict {selected_stat}...")

# Define feature columns specific to the stat
feature_columns = [f"{selected_stat}_avg", f"opponent_avg_conceded_{selected_stat}", "days_since_last_game"]

for add_stat in additional_stats:
    feature_columns.extend([f"{add_stat}_avg", f"opponent_avg_conceded_{add_stat}"])

print("Feature columns:", feature_columns)

# Drop rows with NaN values in feature columns for training and testing
X_train = train_data[feature_columns].dropna()
y_train = train_data.loc[X_train.index, selected_stat]  # Align target with filtered features
X_test = test_data[feature_columns].dropna()
y_test = test_data.loc[X_test.index, selected_stat]  # Align target with filtered features

# Initialize and train the model
model = RandomForestRegressor(random_state=42, n_estimators=100)
model.fit(X_train, y_train)

# Predict and evaluate
y_pred = model.predict(X_test)
mse_result = mean_squared_error(y_test, y_pred)
mae_result = mean_absolute_error(y_test, y_pred)

# Display results
print(f"Stat: {selected_stat}, Test MSE: {mse_result:.4f}, Test MAE: {mae_result:.4f}")

Training model to predict pts...
Feature columns: ['pts_avg', 'opponent_avg_conceded_pts', 'days_since_last_game', 'fg_pct_avg', 'opponent_avg_conceded_fg_pct']
Stat: pts, Test MSE: 41.0467, Test MAE: 4.9706

In [ ]:
results_df = pd.DataFrame({
    'Actual': y_test.values,
    'Predicted': y_pred
})

results_df["Difference"] = results_df.apply(lambda x: x["Actual"] - x["Predicted"], axis=1)
results_df["Negative Diff"] = results_df["Difference"] > 0

display(results_df)

total_pos_diff = results_df["Negative Diff"].sum()
print("Positive difference:", total_pos_diff/len(results_df))

results_df.to_csv("results.csv", index=False)

      Actual  Predicted  Difference  Negative Diff
0         18      11.95        6.05           True
1         36      25.53       10.47           True
2          4       4.58       -0.58          False
3         24      12.60       11.40           True
4         12      11.76        0.24           True
...      ...        ...         ...            ...
6176      16       9.81        6.19           True
6177      20      16.44        3.56           True
6178      13      21.08       -8.08          False
6179      17       9.51        7.49           True
6180       0       6.10       -6.10          False

[6181 rows x 4 columns]

Positive difference: 0.44119074583400747

In [95]:
# Define confidence interval based on historical model error
confidence_margin = mae_result  # Example: based on standard deviation or MAE of past predictions

# Calculate theoretical bounds
results_df['Lower_Bound'] = results_df['Predicted'] - confidence_margin
results_df['Upper_Bound'] = results_df['Predicted'] + confidence_margin

# Simulate betting strategy
def betting_decision(row, theoretical_line):
    if theoretical_line > row['Upper_Bound']:
        return 'Bet Under'
    elif theoretical_line < row['Lower_Bound']:
        return 'Bet Over'
    else:
        return 'No Bet'

# Apply betting decisions for future games
theoretical_line = 25  # Example: set a constant or dynamic theoretical line
results_df['Bet_Suggestion'] = results_df.apply(lambda row: betting_decision(row, theoretical_line), axis=1)

# Display results
print(results_df[['Predicted', 'Lower_Bound', 'Upper_Bound', 'Bet_Suggestion']])

      Predicted  Lower_Bound  Upper_Bound Bet_Suggestion
0         11.95     6.979352    16.920648      Bet Under
1         25.53    20.559352    30.500648         No Bet
2          4.58    -0.390648     9.550648      Bet Under
3         12.60     7.629352    17.570648      Bet Under
4         11.76     6.789352    16.730648      Bet Under
...         ...          ...          ...            ...
6176       9.81     4.839352    14.780648      Bet Under
6177      16.44    11.469352    21.410648      Bet Under
6178      21.08    16.109352    26.050648         No Bet
6179       9.51     4.539352    14.480648      Bet Under
6180       6.10     1.129352    11.070648      Bet Under

[6181 rows x 4 columns]

In [99]:
if save_pipeline:
    path = f"../dist/betting"
    
    save_file(path, model, f"{selected_stat}")